schema_version = "1.0.0"

id = "startup"
version = "0.2.19"
name = "OmooLab Startup"
tagline = "Use OmooLab Startup"
maintainer = "Nan"
type = "add-on"

blender_version_min = "4.5.0"
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
clipboard = "Paste clipboard images into Blender"
files = "Temporarily load generated previews and clipboard images before packing"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
]
